# Generated by Django 4.0.1 on 2022-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
