# Generated by Django 4.0.1 on 2022-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile-images'),
        ),
    ]
